### ISSUE TITLE
Query Provider : query prrovider does not give priority to deployment queries.

### ISSUE THREAD

**Issue by Yasara123** [wso2/carbon-analytics-common#495]
**Description:**
Query prrovider does not give priority to deployment queries it giving priority to default queries.

**Suggested Labels:**
Bug

**Suggested Assignees:**
@ksdperera

**Comment by ksdperera** [comment]
Hi,

Can you explain the requirement ? Why we need to override default version queries. Because deployment yaml is uses for override the queries for particular database version. Then you have to specify the database version  when you override the configuration in deployment yaml

**Comment by ksdperera** [comment]
Close as there is no valid requirement for override the default version queries pack with Component.
This functionality uses for override the particular database version where the default queries doesn't  support. If you need to override you can specify the database version and name in deployment yaml at that time query provider prioritize the deployment queries.

Please raised if there are any valid concern  for such functionality.
