### ISSUE TITLE
Task was rejected due to the worker threads being busy

### ISSUE THREAD

**Issue by Methma** [wso2/carbon-analytics-common#562]
**Description:**

The Following ERROR observed in **wso2das-3.1.0+1536386291526.full.zip** when publishing events with a heavy load to DAS.

> TID: [-1] [] [2018-09-20 13:45:37,441]  WARN {org.apache.thrift.server.TThreadPoolServer} -  Task has been rejected by ExecutorService 9 times till timedout, reason: java.util.concurrent.RejectedExecutionException: Task org.apache.thrift.server.TThreadPoolServer$WorkerProcess@410550ea rejected from java.util.concurrent.ThreadPoolExecutor@1c374152[Running, pool size = 20, active threads = 20, queued tasks = 0, completed tasks = 34971] {org.apache.thrift.server.TThreadPoolServer}

**Affected Product Version:**
DAS 3.1.0

**Comment by Niveathika92** [comment]
Closing as this is fixed by https://github.com/wso2/carbon-analytics-common/pull/563
